### PR TITLE
fix interpreter globals collision with multiple message templates or modules

### PR DESCRIPTION
**Pull request by dirk-thomas**
Addresses #53.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
+1 from me, fixes #53.

Tested on Hydro and Indigo.

**Comment by gavanderhoorn** [comment]
Ping?

**Comment by dirk-thomas** [comment]
Do you need the fix to be backported to _Hydro_ too? Or is just _Indigo_ fine?

**Comment by gavanderhoorn** [comment]
On 9-10-2014 20:42, Dirk Thomas wrote:

> Do you need the fix to be backported to _Hydro_ too? Or is just _Indigo_ fine?

Yes, getting this in Hydro would be very much appreciated.

thanks

**Comment by dirk-thomas** [comment]
I will try to get it released into both within the next week (together with some other core packages). Is that early enough for you?

**Comment by gavanderhoorn** [comment]
On 9-10-2014 21:08, Dirk Thomas wrote:

> I will try to get it released into both within the next week (together with some other core packages). Is that early enough for you?

Sure, that would be fine.

Thanks again Dirk.

**Comment by dirk-thomas** [comment]
Create new hydro-devel branch and use it: ros/rosdistro@627030425e9d5e536d85d198f418b3f5c18ed18d ros-gbp/genmsg-release@a46e22569475fd8004e28f3867227cb04ad8be5b

Cherry-picked: 4a136e20069b7e735a083a26f6771ffb4df4a1e8

**Comment by dirk-thomas** [comment]
Release pending: ros/rosdistro#5975 ros/rosdistro#5976

**Comment by gavanderhoorn** [comment]
Thanks again for the quick turnaround.

**Pull request merged**
