### PR TITLE
resolve path of message file and include dirs in installspace at runtime (ros/catkin#490)

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by jbohren** [comment]
Now that the paths in `${${package}_MESSAGE_FILES}` are relative, what is the proper way to actually get the absolute path to the file?

Is there a better way than the following?:

``` cmake
set(MSG_FILES)                                            
foreach(FILE_REL ${${package}_MESSAGE_FILES})             
  list(APPEND MSG_FILES ${${package}_DIR}/../${FILE_REL}) 
endforeach()                                              
```

**Comment by jbohren** [comment]
Also,  it looks like `${${package}_SERVICE_FILES}` is still an absolute path in genmsg 4.22.

**Comment by dirk-thomas** [comment]
Yes, that would be the right way to construct the absolute paths.

Good catch regarding the service files. I have fixed them in the recent commit.

**Pull request merged**
