### PR TITLE
speed up generate_messages() macro

### PR DESCRIPTION
**Pull request by jbrindza**
This patch implements the generate_messages() macro using just cmake. Removing the python calls provides a significant performance increase. From my tests I've found it to be ~0.2s faster on average. In our project we have ~30 packages that generate messages or services and it saved ~8 seconds off our cmake configure step.

Also, I went with option 1 for #41 as we felt the build should be automatic to and incurring a reconfigure in our project is a small time cost.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Thank you for your pull request.

While the proposed patch might improve the runtime by 0.2s per package it introduces a lot of CMake code which already exists (in a much shorter form) in Python and is also covered by unit tests. Therefore I am not convinced that the runtime improvement is worth the effort of maintaining this big chunk of additional CMake code.

**Comment by wjwwood** [comment]
Omg, that is both impressive and masochistic, I appreciate the effort you put into this, but I am concerned about maintaining that CMake code....

Is there anyway we could meet in the middle and improve the performance while leaving the code in Python? For example, it maybe that we can do one bulk call to Python per message package (if that is not already the case)?

**Comment by jbrindza** [comment]
That's fine, I didn't really expect you to accept it. I just thought it might be of interest to anyone else who also valued compile time speedups. We wanted to speed up our configure step for our cmake project and found that the generate_messages() calls were the main bottleneck. This change provided a > 40% improvement in overall run time.

Currently you make two python calls per package. You can easily remove the first one (which doesn't use any of the python code anyway) and still get a noticeable improvement. The `configure_msg_include_dirs()` macro, lines 481-495, is the cmake code needed to replace it.
Unfortunately, it seems like almost all the overhead is in making the execute_process(python) call in the first place.

**Comment by dirk-thomas** [comment]
I have created #44 which refactors the generation of the pkg-msg-paths.cmake files to use `configure_file()` rather then `empy`.

As mentioned before the "other half" of this pull request (reimplement genmsg stuff in CMake) won't be merged due to the implications of the additional complex CMake code. I will mark this as "wontfix" - if others find it valuable they can still use your branch.

**Comment by ahundt** [comment]
This patch is also very useful to me, and it helps make it easier/possible to use non catkin cmake for ros packages.

**Comment by wjwwood** [comment]
@ahundt can you expand on that? Do you mean that it makes it easier to make ROS packages which do not rely on catkin? How does this pull request change that?

**Comment by ahundt** [comment]
Yes, this lets me include the code that calls generate_messages() without initializing catkin. Trying to do the same without this patch wasn't really easy/possible because I run into quite a few errors and variables that are not set. Ultimately, none, or at least less, of those extra catkin specific variables and configuration is necessary if genmsg is supplied in the pure cmake form used by this patch. 

I'm building my tools using a [separate utility](http://opensource.andreasschuh.com/cmake-basis/), as I mentioned in another (admittedly vague) issue about the [performance problems in catkin](https://github.com/ros/catkin/issues/605).

**Comment by dirk-thomas** [comment]
@ahundt If you have a specific use case which does not work for you please consider either asking a questions on answers.ros.org or filling a separate ticket (if you feel confident that it is a bug and not a usage problem). Anyway please make sure to provide enough information for others to reproduce your use case (e.g. a command sequence or detailed step-by-step descriptions).

**Pull request closed without merging**
