### PR TITLE
Cleaned up base.py

### PR DESCRIPTION
**Pull request by octopuscabbage**
Removed redundant global statements, and added some short circuit logic
which would handle if verbose was somehow set to None or a non boolean
type, plus implimented some short circuit logic.

### CODE REVIEW

**Comment by octopuscabbage** [comment]
I'm not 100% sure the short circuiting helped that much, but the global statements were redundant with the already global declarations of the verboes variable.

If the short circuiting is found to hurt readability too much, I can remove that but keep the global removal.

**Comment by tfoote** [comment]
@ros-pull-request-builder

**Comment by octopuscabbage** [comment]
I've added another change which should reduce some state machine based confusion in msgs.py. Sorry, I should've included that in my original pull request.

**Comment by dirk-thomas** [comment]
For some of the changes (second commit) I disagree that they are improving the code readability. At least not significantly enough to justify to diverge the different branches.

For the first commit I added a comment to replace the state variables and enums with a simple enum.

**Comment by dirk-thomas** [comment]
Please consider addressing the feedback.

**Comment by octopuscabbage** [comment]
sorry, i've been away for a bit. I'll undo the changes for readability and change that to a boolean.

**Comment by octopuscabbage** [comment]
it should be correct now.

**Comment by dirk-thomas** [comment]
My previous comment still applies:

```
The global keyword might be not strictly necessary but it improves the readability of the code by pointing out explicitly that a global variable is used.
```

Also the changes in the base.py file use tabs instead of spaces. Please stick to PEP8.

**Comment by octopuscabbage** [comment]
But I disagree on that point, the global keyword kind of implies that you are changing the scope of a variable from some other scope to local. 

See here: https://docs.python.org/2/reference/simple_stmts.html#the-global-statement 

The scope of the variable isn't being changed, it's just being referred to. This actually threw me the first time I read this code, as I thought the variable was being declared locally and then referred to globally. 

I'll make the PEP8 changes in a second, I was using github's editor which I guess preserves tabs.

**Comment by dirk-thomas** [comment]
Since the patch:
- does not contain any functional change
- is still not following the code style (PEP8)
- has still regressions (using `balenced` instead of `balanced` in https://github.com/ros/genmsg/pull/46/files#diff-5bb2fe83686ae26d63b4d02117c3662fR136)
- has no progress since quite some time

I will close this ticket for now. Please feel free to address the comments and the ticket can be reopened any time.

**Pull request closed without merging**
