### PR TITLE
add check for changed message dependencies changed

### PR DESCRIPTION
**Pull request by dirk-thomas**
This will address #41.

@esteve @tfoote @wjwwood Please review.

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by wjwwood** [comment]
+1

**Comment by esteve** [comment]
+1

**Comment by dirk-thomas** [comment]
Looks like nobody saw this line: https://github.com/ros/genmsg/pull/42/files#diff-4550241ab9cfab757dd57568ab830b61R75 :wink:
Removed again in 99c88772eb3e7c5cc86df82342214e634877e15a

**Pull request merged**
